{{- $namespace := .Release.Namespace -}}
{{- if .Values.jobs.userInit }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: user-init
  namespace: osdu-core  # Ensure the correct namespace
spec:
  schedule: "0 0 * * *"  # Adjust the schedule as needed
  suspend: true  # Ensure the job is suspended until manually triggered
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 120
      template:
        spec:
          volumes:
          - name: script
            configMap:
              name: user-init-script
              defaultMode: 0500
          initContainers:
          - name: data-seed
            image: mcr.microsoft.com/cbl-mariner/base/core:2.0
            command: ["/bin/sh"]
            args:
            - -c
            - |
              tdnf install -y curl jq && \
              /script/example.sh
            volumeMounts:
              - name: script
                mountPath: "/script"
            env:
              - name: AUTH_CODE
                value: ""  # Placeholder value
              - name: AZURE_TENANT_ID
                value: {{ .Values.tenantId | quote }}
              - name: AZURE_CLIENT_ID
                value: {{ .Values.clientId | quote }}
              - name: AZURE_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.clientSecret.name | quote }}
                    key: {{ .Values.clientSecret.key | quote }}
          containers:
          - name: sleep
            image: istio/base
            command: ["/bin/sleep", "10"]
          restartPolicy: Never
      backoffLimit: 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-init-script
  namespace: osdu-core  # Ensure the correct namespace
data:
  example.sh: |
    #!/bin/sh
    echo "Hello, Kubernetes! The auth code is: $AUTH_CODE"
    # Add your script logic here
{{- end }}
