apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blob-csi-driver
  namespace: default
spec:
  targetNamespace: kube-system
  releaseName: blob-csi-driver
  chart:
    spec:
      chart: blob-csi-driver
      version: v1.26.1
      sourceRef:
        kind: HelmRepository
        name: blob-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values       
      valuesKey: values.yaml
  values:
    blobfuse2:
      enabled: true
    node:
      tokenRequests:
        - audience: api://AzureADTokenExchange
      tolerations:
        - key: kubernetes.azure.com/role
          operator: Equal
          value: agent
          effect: NoSchedule
    controller:
      replicas: 1
      runOnControlPlane: false
    serviceAccount:
      create: true
      controller: csi-blob-controller-sa
      node: csi-blob-node-sa
