{{- if .Values.ingress.externalGateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: external-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress-external
  servers:
    - port:
        name: http2
        number: 80
        protocol: HTTP2
      hosts:
        - {{ .Values.ingress.externalGateway.hosts | join ", " }}
    - port:
        name: https
        number: 443
        protocol: HTTPS
      hosts:
        - {{ .Values.ingress.externalGateway.hosts | join ", " }}
      tls:
        mode: {{ .Values.ingress.externalGateway.tls.mode }}
        credentialName: {{ .Values.ingress.externalGateway.tls.credentialName }}
{{- end }}