{{- define "gateway" -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .name | default (printf "%s-gateway" .gatewayType) }}
  namespace: istio-system
spec:
  selector:
    {{- .selector | default (dict "istio" (printf "ingress-%s" .gatewayType)) | toYaml | nindent 4 }}
  servers:
    - port:
        name: http2
        number: 80
        protocol: HTTP2
      hosts:
        {{- if .hosts }}
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- else }}
        - "*"
        {{- end }}
      {{- if .cors }}
      corsPolicy:
        allowOrigins:
          {{- range .cors.allowOrigins }}
          - exact: {{ . | quote }}
          {{- end }}
        allowMethods:
          {{- range .cors.allowMethods }}
          - {{ . | quote }}
          {{- end }}
        allowHeaders:
          {{- range .cors.allowHeaders }}
          - {{ . | quote }}
          {{- end }}
        maxAge: {{ .cors.maxAge | quote }}
        allowCredentials: {{ .cors.allow_credentials }}
      {{- end }}
    - port:
        name: https
        number: 443
        protocol: HTTPS
      hosts:
        {{- if .hosts }}
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
        {{- else }}
        - "*"
        {{- end }}
      tls:
        {{- if .requireSSL }}
        httpsRedirect: true # sends 301 redirect for http requests
        {{- end }}
        {{- with .tls }}
        {{- toYaml . | nindent 8 }}  
        {{- end }}
      {{- if .cors }}
      corsPolicy:
        allowOrigins:
          {{- range .cors.allowOrigins }}
          - exact: {{ . | quote }}
          {{- end }}
        allowMethods:
          {{- range .cors.allowMethods }}
          - {{ . | quote }}
          {{- end }}
        allowHeaders:
          {{- range .cors.allowHeaders }}
          - {{ . | quote }}
          {{- end }}
        maxAge: {{ .cors.maxAge | quote }}
        allowCredentials: {{ .cors.allow_credentials }}
      {{- end }}
{{- end }}

{{- $internalGateway := merge (dict "gatewayType" "internal") .Values.ingress.internalGateway .Values.internalGateway }}
{{- $externalGateway := merge (dict "gatewayType" "external") .Values.ingress.externalGateway .Values.externalGateway }}
{{ include "gateway" $internalGateway }}
{{ include "gateway" $externalGateway }}