{{- if .Values.ingress.internalGateway.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress-internal
  servers:
    - port:
        name: http2
        number: 80
        protocol: HTTP2
      hosts:
        - {{ .Values.ingress.internalGateway.hosts | join ", " }}
      {{- if .Values.ingress.internalGateway.tls }}
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
      {{- end }}
    - port:
        name: https
        number: 443
        protocol: HTTPS
      hosts:
        - {{ .Values..ingress.internalGateway.hosts | join ", " }}
      {{- if .Values.ingress.internalGateway.tls }}
      tls:
        mode: {{ .Values.ingress.internalGateway.tls.mode }}
        credentialName: {{ .Values.ingress.internalGateway.tls.credentialName }}
      {{- end }}
{{- end }}