# ReferenceGrants are now managed by individual application charts
# to avoid namespace dependency issues during deployment:
# - web-site ReferenceGrant is in software/applications/web-site/
# - cert-manager ReferenceGrant is managed by cert-manager operator
#
# This approach ensures that:
# 1. istio-ingress can deploy without waiting for application namespaces
# 2. Each application manages its own cross-namespace access permissions
# 3. No circular dependencies between infrastructure and applications
