apiVersion: v2
name: osdu-developer-init
type: application
description: Installs the OSDU developer Initialization resources
version: 0.0.6
appVersion: 0.0.1
maintainers:
  - name: danielscholl
    url: https://github.com/azure/osdu-developer