jobs:
  entitlementInit: true
  partitionInit: true
tenantId: <your_tenant_id>
clientId: <your_client_id>
clientSecret:
  name: active-directory
  key: principal-clientpassword
partition: opendes
serviceBus: <your_service_bus_name>