Infrastructure:
  - bicep/main.js
  - bicep/private/modules/**/*

# Add 'documentation' label to any change to *.md files
Documentation:
  - "*.md"
  - "docs/*.md"

Software:
  - software/**/*
  - stamp/**/*
  - charts/**/*