Documentation:
- changed-files:
  - any-glob-to-any-file: ['docs/**', '**/*.md']

Infrastructure:
- changed-files:
  - any-glob-to-any-file: ['bicep/**']
  - all-globs-to-all-files: '!bicep/*.md'

Software:
- changed-files:
  - any-glob-to-any-file: ['software/**', 'stamp/**', 'charts/**']
  - all-globs-to-all-files: ['!software/*.md', '!stamp/*.md', '!charts/*.md']