{{- if .Values.azure.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "azure-keyvault"
spec:
  provider: azure
  secretObjects:
  - secretName: common-storage-account
    type: Opaque
    data: 
    - objectName: common-storage
      key: azurestorageaccountname
    - objectName: common-storage-key
      key: azurestorageaccountkey
  - secretName: common-secrets
    type: Opaque
    data:
    - objectName: graph-db-connection
      key: database-connection
    - objectName: common-storage-key
      key: storage-key
    - objectName: log-workspace-key
      key: workspace-key
  - secretName: opendes-secrets
    type: Opaque
    data:
    - objectName: opendes-cosmos-connection
      key: database-connection
    - objectName: opendes-cosmos-primary-key
      key: database-key
  parameters:
    clientID: {{ .Values.azure.clientId }} # client id of the Azure AD app/identity to use for workload identity
    keyvaultName: {{ .Values.azure.keyvaultName }} # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: graph-db-connection
          objectType: secret
        - |
          objectName: common-storage
          objectType: secret
        - |
          objectName: common-storage-key
          objectType: secret
        - |
          objectName: log-workspace-key
          objectType: secret
        - |
          objectName: opendes-storage
          objectType: secret
        - |
          objectName: opendes-key
          objectType: secret
        - |
          objectName: opendes-cosmos-connection
          objectType: secret
        - |
          objectName: opendes-cosmos-primary-key
          objectType: secret
    tenantId: {{ .Values.azure.tenantId }} # the tenant ID of the KeyVault
{{- end }}
