{{- if .Values.azure.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "azure-keyvault"
spec:
  provider: azure
  secretObjects:
  - secretName: active-directory
    type: Opaque
    data:
    - objectName: "tenant-id"
      key: tenant-id
    - objectName: "app-dev-sp-id"
      key: app-dev-sp-id
  parameters:
    clientID: {{ .Values.azure.clientId }} # client id of the Azure AD app/identity to use for workload identity
    keyvaultName: {{ .Values.azure.keyvaultName }} # the name of the KeyVault
    objects: |
      array:
        - |
          objectName: tenant-id
          objectType: secret
        - |
          objectName: app-dev-sp-id
          objectType: secret
    tenantId: {{ .Values.azure.tenantId }} # the tenant ID of the KeyVault
{{- end }}
