{{- $namespace := .Release.Namespace }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "env-debug.fullname" . }}-pv
  namespace: {{ $namespace }}
  labels:
    usage: file-mount
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  azureFile:
    secretName: common-storage-account
    shareName: sample-share
  volumeMode: Filesystem
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "env-debug.fullname" . }}-pvc
  namespace: {{ $namespace }}
spec:
  storageClassName: "" 
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      usage: file-mount