version: '3.8'

services:
  bun-app:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
