---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  labels:
    istio-injection: disabled
    toolkit.fluxcd.io/tenant: component
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cpng
  namespace: flux-system
spec:
  interval: 5m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-operator
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  releaseName: cnpg-operator
  chart:
    spec:
      chart: cloudnative-pg 
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 10m0s