---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-system
  labels:
    istio-injection: disabled
    toolkit.fluxcd.io/tenant: component
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: flux-system
spec:
  targetNamespace: elastic-system
  releaseName: elastic-operator
  chart:
    spec:
      chart: ./deploy/eck-operator
      sourceRef:
        kind: GitRepository
        name: elastic-operator
        namespace: flux-system
  install:
    remediation:
      retries: 3
  interval: 10m0s