apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: file
  namespace: osdu-azure
spec:
  hosts:
    - "*"
  gateways:
    - aks-istio-ingress/istio-external-gateway
    - aks-istio-ingress/istio-internal-gateway
  http:
    - match:
        - uri:
            prefix: "/api/file/"
      route:
        - destination:
            host: "file.osdu-azure.svc.cluster.local"
            port:
              number: 80
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: file-service
  namespace: osdu-azure
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
  - name: osdu-developer-base
    namespace: default
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
    configuration:
    - service: file
      repository: community.opengroup.org:5555/osdu/platform/system/file/file-azure-m18-master
      tag: latest
      path: /api/file/*
      probe:
        path: /api/file/v2/readiness_check
        port: http
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/file/swagger-resources/*"
          - "/api/file/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: file
      - name: server.servlet.contextPath
        value: /api/file/
      - name: appinsights_key
        value: ""
      - name: server_port
        value: 80
      - name: ACCEPT_HTTP
        value: true
      - name: cosmosdb_database
        value: osdu-db
      - name: LOG_PREFIX
        value: file
      - name: osdu_entitlements_url
        value: http://entitlements/api/entitlements/v2
      - name: osdu_entitlements_app_key
        value: OBSOLETE
      - name: APPLICATION_PORT
        value: 80
      - name: SEARCH_HOST
        value: http://search/api/search/v2
      - name: osdu_storage_url
        value: http://storage/api/storage/v2
      - name: partition_service_endpoint
        value: http://partition/api/partition/v1
      - name: azure_istioauth_enabled
        value: "true"
      - name: azure_istio_corsEnabled
        value: "false"
      - name: BATCH_SIZE
        value: "100"
      - name: SEARCH_QUERY_LIMIT
        value: "1000"
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: authorizeAPI
        value: http://entitlements/api/entitlements/v2
      - name: SPRING_CONFIG_NAME
        value: "common,application"
      - name: event_grid_topic_status
        value: "statuschangedtopic"
      - name: service_bus_topic_status
        value: "statuschangedtopic"
      - name: azure_pubsub_publish
        value: "true"
      - name: FILE_CHECKSUM_CALCULATION_LIMIT
        value: "5368709120L"
      # Notification v2 not enabled (https://community.opengroup.org/osdu/platform/system/file/-/blob/v0.15.0/devops/azure/chart/templates/deployment.yaml#L138)
      - name: service_bus_enabled_status
        value: "true"
      - name: event_grid_enabled_status
        value: "false"
      - name: aad_client_id
        value: "api://"
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URL
        secret:
          name: azure-resources
          key: keyvault-uri
      - name: AZURE_AD_APP_RESOURCE_ID
        secret:
          name: active-directory
          key: principal-clientid