apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: legal
  namespace: osdu-azure
spec:
  hosts:
    - "*"
  gateways:
    - aks-istio-ingress/istio-external-gateway
    - aks-istio-ingress/istio-internal-gateway
  http:
    - match:
        - uri:
            prefix: "/api/legal/v1/"
      route:
        - destination:
            host: "legal.osdu-azure.svc.cluster.local"
            port:
              number: 80
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: legal-service
  namespace: osdu-azure
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
  - name: osdu-developer-base
    namespace: default
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
    configuration:
    - service: legal
      repository: community.opengroup.org:5555/osdu/platform/security-and-compliance/legal/legal-release-0-22
      tag: latest
      path: /api/legal/v1/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/legal/v1/swagger-resources/*"
          - "/api/legal/v1/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: "legal"
      - name: server.servlet.contextPath
        value: "/api/legal/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: cosmosdb_database
        value: "osdu-db"
      - name: LOG_PREFIX
        value: "legal"
      - name: azure_storage_container_name
        value: "legal-service-azure-configuration"
      - name: azure_storage_enable_https
        value: "true"
      - name: legal_service_region
        value: "us"
      - name: servicebus_topic_name
        value: "legaltags"
      - name: entitlements_service_endpoint
        value: "http://entitlements/api/entitlements/v2"
      - name: entitlements_service_api_key
        value: "OBSOLETE"
      - name: partition_service_endpoint
        value: "http://partition/api/partition/v1"
      - name: azure_istioauth_enabled
        value: "true"
      - name: SPRING_CONFIG_NAME
        value: "common,application"
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: REDIS_DATABASE
        value: "2"
      - name: aad_client_id
        value: "api://"
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri