---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-services
  namespace: osdu-azure
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
  - name: osdu-developer-base
    namespace: default
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
    configuration:
    - service: partition
      repository: community.opengroup.org:5555/osdu/platform/system/partition/partition-azure-m18-master
      tag: latest
      path: /api/partition/v1/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v1/api-docs"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "*/swagger"
          - "*/swagger-ui.html"
          - "*/swagger-resources"
          - "/api/partition/v1/swagger-resources/*"
          - "/api/partition/v1/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: "partition"
      - name: server.servlet.contextPath
        value: "/api/partition/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: partition_spring_logging_level
        value: "INFO"
      - name: appinsights_key
        value: ""
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: azure_istioauth_enabled
        value: "true"
      - name: azure_istio_corsEnabled
        value: "false"
      - name: aad_client_id
        value: "api://"
      - name: REDIS_DATABASE
        value: "2"
      - name: azure_msi_client_id
        secret:
          name: active-directory
          key: msi-clientid
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri
########################################
############  ENTITLEMENTS  ############
    - service: entitlements
      repository: community.opengroup.org:5555/osdu/platform/security-and-compliance/entitlements/entitlements-azure-m18-master
      tag: latest
      path: /api/entitlements/v2/*
      probe:
        path: /api/entitlements/v2/_ah/readiness_check
        port: http
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/actuator/health"
          - "*/health"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/entitlements/v2/info"
          - "/api/entitlements/v2/swagger-resources/*"
          - "/api/entitlements/v2/webjars/*"
      env:
      - name: spring_application_name
        value: "entitlements"
      - name: server.servlet.contextPath
        value: "/api/entitlements/v2/"
      - name: LOGGING_LEVEL
        value: "INFO"
      - name: server_port
        value: "80"
      - name: service_domain_name
        value: "contoso.com"
      - name: root_data_group_quota
        value: "5000"
      - name: redis_ttl_seconds
        value: "1"
      - name: partition_service_endpoint
        value: "http://partition/api/partition/v1"
      - name: azure_istioauth_enabled
        value: "true"
      - name: azure_activedirectory_AppIdUri
        value: "api://"
      - name: azure_paas_podIdentity_isEnabled
        value: "false"
      - name: azure_msi_client_id
        secret:
          name: active-directory
          key: msi-clientid
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri
########################################
###############  LEGAL  ################
    - service: legal
      repository: community.opengroup.org:5555/osdu/platform/security-and-compliance/legal/legal-azure-m18-master
      tag: latest
      path: /api/legal/v1/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/legal/v1/swagger-resources/*"
          - "/api/legal/v1/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: "legal"
      - name: server.servlet.contextPath
        value: "/api/legal/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: cosmosdb_database
        value: "osdu-db"
      - name: LOG_PREFIX
        value: "legal"
      - name: azure_storage_container_name
        value: "legal-service-azure-configuration"
      - name: azure_storage_enable_https
        value: "true"
      - name: legal_service_region
        value: "us"
      - name: servicebus_topic_name
        value: "legaltags"
      - name: entitlements_service_endpoint
        value: "http://entitlements/api/entitlements/v2"
      - name: entitlements_service_api_key
        value: "OBSOLETE"
      - name: partition_service_endpoint
        value: "http://partition/api/partition/v1"
      - name: azure_istioauth_enabled
        value: "true"
      - name: SPRING_CONFIG_NAME
        value: "common,application"
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: REDIS_DATABASE
        value: "2"
      - name: aad_client_id
        value: "api://"
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri
########################################
###############  SCHEMA  ###############
    - service: schema
      repository: community.opengroup.org:5555/osdu/platform/system/schema-service/schema-service-azure-m18-master
      tag: latest
      path: /api/schema-service/v1/*
      probe:
        path: /api/schema-service/v1/swagger-ui.html
        port: http
      keyvault: true
      auth:
        disable:
        - "*/index.html"
        - "*/swagger"
        - "/api/schema-service/v1/swagger-ui/*"
        - "/api/schema-service/v1/v3/api-docs/*"
        - "*/swagger-config"
        - "*/v1/api-docs"
        - "*/api-docs.yaml"
        - "*/actuator/health"
        - "*/_ah/**"
        - "/api/schema-service/v1/info"
      env:
      - name: spring_application_name
        value: "schema"
      - name: server.servlet.contextPath
        value: "/api/schema-service/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: cosmosdb_database
        value: "osdu-db"
      - name: LOG_PREFIX
        value: "schema"
      - name: entitlements_service_endpoint
        value: "http://entitlements/api/entitlements/v2"
      - name: entitlements_service_api_key
        value: "OBSOLETE"
      - name: partition_service_endpoint
        value: "http://partition/api/partition/v1"
      - name: shared_partition
        value: "opendes"
      - name: azure_istioauth_enabled
        value: "true"
      - name: event_grid_enabled
        value: "false"
      - name: event_grid_topic
        value: "schemachangedtopic"
      - name: azure_paas_podIdentity_isEnabled
        value: "false"
      - name: aad_client_id
        value: "api://"
      - name: servicebus_topic_name
        value: schemachangedtopic
      - name: event_grid_enabled
        value: 'false'
      - name: service_bus_enabled
        value: 'true'
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri