apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: partition
  namespace: osdu-azure
spec:
  hosts:
    - "*"
  gateways:
    - aks-istio-ingress/istio-external-gateway
    - aks-istio-ingress/istio-internal-gateway
  http:
    - match:
        - uri:
            prefix: "/api/partition/v1/"
      route:
        - destination:
            host: "partition.osdu-azure.svc.cluster.local"
            port:
              number: 80
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partition-service
  namespace: osdu-azure
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
  - name: osdu-developer-base
    namespace: default
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  values:
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
    configuration:
    - service: partition
      repository: community.opengroup.org:5555/osdu/platform/system/partition/partition-azure-m18-master
      tag: latest
      path: /api/partition/v1/*
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v1/api-docs"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "*/swagger"
          - "*/swagger-ui.html"
          - "*/swagger-resources"
          - "/api/partition/v1/swagger-resources/*"
          - "/api/partition/v1/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: spring_application_name
        value: "partition"
      - name: server.servlet.contextPath
        value: "/api/partition/v1/"
      - name: server_port
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: partition_spring_logging_level
        value: "INFO"
      - name: appinsights_key
        value: ""
      - name: azure_paas_podIdentity_isEnabled
        value: "true"
      - name: azure_istioauth_enabled
        value: "true"
      - name: azure_istio_corsEnabled
        value: "false"
      - name: aad_client_id
        value: "api://"
      - name: REDIS_DATABASE
        value: "2"
      - name: azure_msi_client_id
        secret:
          name: active-directory
          key: msi-clientid
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri