---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-developer-base
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  chart:
    spec:
      chart: ./charts/osdu-developer-base
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    azure:
      enabled: true
    resourceLimits:
      defaultCpuRequests: "0.5"
      defaultMemoryRequests: "4Gi"
      defaultCpuLimits: "1"
      defaultMemoryLimits: "4Gi"