apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-keyvault
spec:
  provider: azure
  secretObjects:
  {{- range .Values.secrets }}
  - secretName: {{ .secretName }}
    type: Opaque
    data:
    {{- range .data }}
    - objectName: "{{ .vaultSecret }}"
      key: {{ .key }}
    {{- end }}
  {{- end }}
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.azure.clientId }} # client id of the Azure AD app/identity to use for workload identity
    keyvaultName: {{ .Values.azure.keyvaultName }} # the name of the KeyVault
    tenantId: {{ .Values.azure.tenantId }} # the tenant id of the KeyVault
    objects: |
      array:
      {{- range .Values.secrets }}
        {{- range .data }}
        - |
          objectName: {{ .vaultSecret }}
          objectType: secret
        {{- end }}
      {{- end }}