{{- $namespace := .Release.Namespace }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "app-config.fullname" . }}-config
  namespace: {{ $namespace }}
spec:
  endpoint: {{ .Values.appConfiguration.endpoint }}
  target:
    configMapName: configmap-created-by-appconfig-provider
    configMapData: 
      type: json
      key: mysettings.json
  auth:
    workloadIdentity:
      managedIdentityClientId: {{ .Values.azureWorkloadIdentity.clientId }}