---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-sample
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  chart:
    spec:
      chart: ./charts/env-debug
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: dev-sample
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: env-debug
    azure:
      enabled: true
    service:
      type: ClusterIP
      port: 80
    env:
    - name: MESSAGE
      value: Hello World!
    - name: FROM_CONFIG_MAP
      valueFrom:
        configMapKeyRef:
          name: env-debug-config
          key: MESSAGE
    - name: WORKSPACE_KEY
      secret:
        name: common-secrets
        key: workspace-key
    - name: STORAGE_KEY
      secret:
        name: common-secrets
        key: storage-key
    - name: DATABASE_CONNECTION
      secret:
        name: common-secrets
        key: database-connection
    
    
