---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/env-debug
      sourceRef:
        kind: GitRepository
        name: osdu-developer
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: default
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: env-debug
    service:
      type: ClusterIP
      port: 80
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    azure:
      enabled: false
    env:
    - name: MESSAGE
      value: Hello World!
    # - name: AZURE_TENANT_ID
    #   secret:
    #     name: active-directory
    #     key: tenantid
    # - name: WORKSPACE_ID
    #   secret:
    #     name: central-logging
    #     key: workspace-id