---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dev-sample
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  chart:
    spec:
      chart: ./charts/env-debug
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: dev-sample
  valuesFrom:
    - kind: ConfigMap
      name: workload-identity-values
      valuesKey: values.yaml
  values:
    replicaCount: 1
    nameOverride: ""
    fullnameOverride: env-debug
    service:
      type: ClusterIP
      port: 80
    azure:
      enabled: false
    env:
    - name: MESSAGE
      value: Hello World!
    - name: FROM_CONFIG_MAP
      valueFrom:
        configMapKeyRef:
          name: env-debug-config
          key: MESSAGE
# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#   name: app-config
#   namespace: default
#   annotations:
#     clusterconfig.azure.com/use-managed-source: "true"
# spec:
#   chart:
#     spec:
#       chart: ./charts/app-config
#       sourceRef:
#         kind: GitRepository
#         name: flux-system
#         namespace: flux-system
#   interval: 5m0s
#   install:
#     remediation:
#       retries: 3
#   targetNamespace: dev-sample
#   valuesFrom:
#     - kind: ConfigMap
#       name: app-config-values
#       valuesKey: values.yaml