apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dns-configuration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dns-configuration.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "dns-configuration.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: istio-ingress-external-dns
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: {{ include "dns-configuration.fullname" . }}-script
          defaultMode: 0755
      containers:
      - name: dns-config
        image: "mcr.microsoft.com/cbl-mariner/base/core:2.0"
        imagePullPolicy: IfNotPresent
        command: ["/scripts/configure-dns.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
        env:
        - name: DNS_NAME
          value: {{ .Values.azure.dnsName | quote }}
        - name: AZURE_REGION
          value: {{ .Values.azure.region | quote }}
        - name: MAX_RETRIES
          value: "60"
        - name: RETRY_INTERVAL
          value: "5"