apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-certs
  namespace: default
spec:
  targetNamespace: osdu-system
  dependsOn:
    - name: istio-ingress-external
      namespace: flux-system
  chart:
    spec:
      chart: ./charts/istio-certs
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 10m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml