apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: ./charts/istio-ingress
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    ingress:
      internalGateway:
        cors:
          allowOrigins:
            - https://example.com
          allowMethods:
            - GET
            - POST
            - OPTIONS
          allowHeaders:
            - Authorization
            - Content-Type
          maxAge: "24h"
      externalGateway:
        cors:
          allowOrigins:
            - https://example.com
          allowMethods:
            - GET
            - POST
            - OPTIONS
          allowHeaders:
            - Authorization
            - Content-Type
          maxAge: "24h"