apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: istio-system
  chart:
    spec:
      chart: ./charts/istio-ingress
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    internalGateway:
      cors:
        allowOrigins:
          - http://localhost:8080
        allowMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
        maxAge: "24h"
        allow_credentials: true
    externalGateway:
      cors:
        allowOrigins:
          - http://localhost:8080
        allowMethods:
          - GET
          - PUT
          - POST
          - DELETE
          - OPTIONS
        allowHeaders:
          - Authorization
          - Content-Type
        maxAge: "24h"
        allow_credentials: true