apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-reader
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-reader-binding
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: workload-identity-sa
  namespace: osdu-experimental
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io