{{- $namespace := .Release.Namespace }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "osdu-developer.fullname" . }}-services
  namespace: {{ $namespace }}
spec:
  endpoint: {{ .Values.azure.configEndpoint }}
  target:
    configMapName: configmap-services
  auth:
    workloadIdentity:
      managedIdentityClientId: {{ .Values.azure.clientId }}
  configuration:
     selectors:
        - keyFilter: "*"
          labelFilter: "configmap-services"