{{- $namespace := .Release.Namespace }}
apiVersion: azconfig.io/v1
kind: AzureAppConfigurationProvider
metadata:
  name: {{ include "osdu-developer.fullname" . }}-values
  namespace: {{ $namespace }}
spec:
  endpoint: {{ .Values.azure.configEndpoint }}
  target:
    configMapName: configmap-common-values
    configMapData:
      type: yaml
      key: value.yaml
      separator: "."
  auth:
    workloadIdentity:
      serviceAccountName: workload-identity-sa
  configuration:
     selectors:
        - keyFilter: "*"
          labelFilter: "configmap-common-values"