{{- $namespace := .Release.Namespace }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: destination-rule
spec:
  host: "*.{{ $namespace }}.svc.cluster.local"
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
    tls:
      mode: ISTIO_MUTUAL
