{{- if .Values.airflow.csvdag.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-csvdag-upload
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: workload-identity-sa
      volumes:
      - name: scripts
        configMap:
          name: csvdag-scripts-{{ .Release.Name }}
          defaultMode: 0500
      - name: share-storage
        persistentVolumeClaim:
          claimName: {{ .Values.airflow.csvdag.pvc }}
      containers:
      - name: csvdag-upload
        image: mcr.microsoft.com/cbl-mariner/base/python:3.9-cm2.0
        command: ["/bin/bash"]
        args:
        - /scripts/csv-dag.sh
        env:
          - name: URL
            value: {{ .Values.airflow.csvdag.url | quote }}
          - name: FILE
            value: {{ .Values.airflow.csvdag.folder | quote }}
          - name: SEARCH_AND_REPLACE
            value: |
              [
                {
                  "find": "{| K8S_POD_OPERATOR_KWARGS or {} |}",
                  "replace": {
                    "annotations": {
                      "sidecar.istio.io/inject": "false"
                    },
                    "labels": {
                      "aadpodidbinding": "osdu-identity"
                    }
                  }
                },
                {
                  "find": "{| ENV_VARS or {} |}",
                  "replace": {
                    "AZURE_CLIENT_ID": {{ .Values.clientId | quote }},
                    "AZURE_CLIENT_SECRET": {{ .Values.secrets.client_key | quote }},
                    "AZURE_TENANT_ID": {{ .Values.tenantId | quote }},
                    "KEYVAULT_URI": {{ .Values.keyvaultUri | quote }},
                    "aad_client_id": {{ .Values.clientId | quote }},
                    "appinsights_key": {{ .Values.appInsightsKey | quote }},
                    "azure_paas_podidentity_isEnabled": "false",
                    "file_service_endpoint": "http://file.osdu-core.svc.cluster.local/api/file/v2",
                    "partition_service_endpoint": "http://partition.osdu-core.svc.cluster.local/api/partition/v1",
                    "schema_service_endpoint": "http://schema.osdu-core.svc.cluster.local/api/schema-service/v1",
                    "search_service_endpoint": "http://search.osdu-core.svc.cluster.local/api/search/v2",
                    "storage_service_endpoint": "http://storage.osdu-core.svc.cluster.local/api/storage/v2",
                    "unit_service_endpoint": "http://unit.osdu-core.svc.cluster.local/api/unit/v2/unit/symbol"
                  }
                }
              ]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: share-storage
          mountPath: /share
      restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csvdag-scripts-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
data:
  replace.py: |
    {{ .Files.Get "scripts/replace.py" | nindent 4 }}
  csv-dag.sh: |
    {{ .Files.Get "scripts/csv-dag.sh" | nindent 4 }}
{{- end }}