---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-variables
  namespace: airflow
data:
  AIRFLOW_VAR_NAMESPACE: "airflow"
  AIRFLOW__METRICS__USE_PATTERN_MATCH: "True"
  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
  AIRFLOW__LOGGING__ENABLE_TASK_CONTEXT_LOGGER: "False"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.default"
  AIRFLOW__CELERY__SSL_ACTIVE: "True"
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
  AIRFLOW_VAR_CORE__CONFIG__DATALOAD_CONFIG_PATH: "/opt/airflow/dags/configs/dataload.ini"
  AIRFLOW__WEBSERVER__WORKERS: "8"
  AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE: "0"
  AIRFLOW__CORE__STORE_SERIALIZED_DAGS: "True"
  AIRFLOW__CORE__STORE_DAG_CODE: "True"
  AIRFLOW__WEBSERVER__WORKER_CLASS: "gevent"
  AIRFLOW__CELERY__WORKER_CONCURRENCY: "16"
  AIRFLOW_VAR_CORE__CONFIG__SHOW_SKIPPED_IDS: "True"
  AIRFLOW_VAR_ENV_VARS_ENABLED: "True"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-service-endpoints
  namespace: airflow
data:
  AIRFLOW_VAR_CORE__SERVICE__PARTITION__URL: "http://partition.osdu-core.svc.cluster.local/api/partition/v1"
  AIRFLOW_VAR_CORE__SERVICE__LEGAL__HOST: "http://legal.osdu-core.svc.cluster.local/api/legal/v1"
  AIRFLOW_VAR_CORE__SERVICE__ENTITLEMENTS__URL: "http://entitlements.osdu-core.svc.cluster.local/api/entitlements/v2"
  AIRFLOW_VAR_CORE__SERVICE__SCHEMA__URL: "http://schema.osdu-core.svc.cluster.local/api/schema-service/v1"
  AIRFLOW_VAR_CORE__SERVICE__SEARCH__URL: "http://search.osdu-core.svc.cluster.local/api/search/v2"
  AIRFLOW_VAR_CORE__SERVICE__SEARCH_WITH_CURSOR__URL: "http://search.osdu-core.svc.cluster.local/api/search/v2/query_with_cursor"
  AIRFLOW_VAR_CORE__SERVICE__STORAGE__URL: "http://storage.osdu-core.svc.cluster.local/api/storage/v2"
  AIRFLOW_VAR_CORE__SERVICE__FILE__HOST: "http://file.osdu-core.svc.cluster.local/api/file"
  AIRFLOW_VAR_CORE__SERVICE__WORKFLOW__HOST: "http://workflow.osdu-core.svc.cluster.local/api/workflow/v1"
  AIRFLOW_VAR_CORE__SERVICE__DATASET__HOST: "http://dataset.osdu-core.svc.cluster.local/api/dataset/v1"