---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-dags
  namespace: airflow
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  targetNamespace: airflow
  releaseName: airflow-dags
  dependsOn:
    - name: azure-keyvault-airflow
      namespace: default
    - name: config-maps-airflow
      namespace: default
  chart:
    spec:
      chart: ./charts/airflow-dags
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
    - kind: Secret
      name: airflow-secrets
      valuesKey: client-key
      targetPath: secrets.airflowSecrets.clientKey
  values:
    airflow:
      manifestdag:
        enabled: true
        items:
        - name: manifest
          folder: "src/osdu_dags"
          compress: true
          url: "https://community.opengroup.org/osdu/platform/data-flow/ingestion/ingestion-dags/-/archive/master/ingestion-dags-master.tar.gz"
          pvc: "airflow-dags-pvc"
      csvdag:
        enabled: true
        folder: "airflowdags"
        compress: true
        url: "https://community.opengroup.org/osdu/platform/data-flow/ingestion/csv-parser/csv-parser/-/archive/master/csv-parser-master.tar.gz"
        pvc: "airflow-dags-pvc"
        replacements:
          - find: '{| K8S_POD_OPERATOR_KWARGS or {} |}'
            replace:
              labels:
                aadpodidbinding: "osdu-identity"
              annotations:
                "sidecar.istio.io/inject": "false"
          - find: '{| ENV_VARS or {} |}'
            replace:
              storage_service_endpoint: "http://storage.osdu-core.svc.cluster.local/api/storage/v2"
              schema_service_endpoint: "http://schema.osdu-core.svc.cluster.local/api/schema-service/v1"
              search_service_endpoint: "http://search.osdu-core.svc.cluster.local/api/search/v2"
              partition_service_endpoint: "http://partition.osdu-core.svc.cluster.local/api/partition/v1"
              unit_service_endpoint: "http://unit.osdu-core.svc.cluster.local/api/unit/v2/unit/symbol"
              file_service_endpoint: "http://file.osdu-core.svc.cluster.local/api/file/v2"
              KEYVAULT_URI: "{{ .Values.keyvaultUri }}"
              appinsights_key: "{{ .Values.appInsightsKey }}"
              azure_paas_podidentity_isEnabled: "false"
              AZURE_TENANT_ID: "{{ .Values.tenantId }}"
              AZURE_CLIENT_ID: "{{ .Values.clientId }}"
              AZURE_CLIENT_SECRET: "{{ .Values.secrets.airflowSecrets.clientKey | default "your-client-secret" }}"
              aad_client_id: "{{ .Values.azure.clientId }}"