---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
  namespace: airflow
  labels:
    usage: airflow-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  azureFile:
    secretName: azure-keyvault
    shareName: sample-share
  volumeMode: Filesystem
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-csi-premium  # Use this for premium Azure Files
  selector:
    matchLabels:
      usage: airflow-pv