---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: flux-system
  labels:
    name: airflow
spec:
  targetNamespace: airflow
  releaseName: airflow
  dependsOn:
    - name: azure-keyvault-airflow
      namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 10
      strategy: rollback
  test:
    enable: true
  interval: 10m0s
  chart:
    spec:
      chart: airflow
      # version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: flux-system
  values:

    # Version Isolation
    airflowVersion: 2.10.1
    defaultAirflowTag: 2.10.1

    # Airflow executor
    executor: KubernetesExecutor

    # Environment variables for all airflow containers
    env:
      - name: ENVIRONMENT
        value: "dev"
      - name: CLOUD_PROVIDER
        value: "azure"
      - name: CI_COMMIT_TAG
        value: "v0.12.0"
      - name: BUILD_TAG
        value: "v0.12.0"
      - name: AIRFLOW_VAR_ENTITLEMENTS_MODULE_NAME
        value: "entitlements_client"

    extraEnv: |
      - name: AIRFLOW_VAR_ANOTHER_KEY
        value: 'value_1'
      
    extraConfigMaps:
      'airflow-variables':
        data: |
          AIRFLOW_VAR_ENV_VARS_ENABLED: "True"
          AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
          AIRFLOW_VAR_CORE__CONFIG__DATALOAD_CONFIG_PATH: "/opt/airflow/dags/configs/dataload.ini"
          AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
          AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
          AIRFLOW__CORE__LOGGING_LEVEL: "INFO"
          AIRFLOW__LOGGING__ENABLE_TASK_CONTEXT_LOGGER: "False"
          AIRFLOW_VAR_NAMESPACE: "airflow"
          AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"

    extraEnvFrom: |
      - configMapRef:
          name: "airflow-variables"
      - secretRef:
          name: 'airflow-variables'

    # Admin user configuration
    admin:
      existingSecret: airflow-secrets
      usernameKey: username
      passwordKey: password

    # Disable the internal PostgreSQL chart
    postgresql:
      enabled: false

    # External PostgreSQL configuration
    data:
      metadataSecretName: airflow-secrets

    # Disable pgbouncer.
    # CloudNativePG provides native support for connection pooling with PgBouncer
    pgbouncer:
      enabled: false

    # StatsD settings
    statsd:
      enabled: true

    # Pull DAGS from file share and from a git repo
    dags:
      persistence:
        enabled: true
        existingClaim: airflow-dags-pvc
      gitSync:
        enabled: false

    logs:
      persistence:
        enabled: true
        existingClaim: airflow-logs-pvc

    config:
      webserver:
        expose_config: 'True'
        instance_name: OSDU
        enable_proxy_fix: 'True'
        # base_url: 'http://localhost/airflow'
      operators:
        default_owner: OSDU

    # We disable the log groomer sidecars because we use Azure File Storage for logs
    triggerer:
      logGroomerSidecar:
        enabled: false
    scheduler:
      logGroomerSidecar:
        enabled: false
    workers:
      logGroomerSidecar:
        enabled: false

    # Ensure we are using the secrets from Azure Key Vault
    enableBuiltInSecretEnvVars:
      AIRFLOW__CORE__FERNET_KEY: false
      AIRFLOW__WEBSERVER__SECRET_KEY: false
    fernetKeySecretName: keyvault-secrets
    webserverSecretKeySecretName: keyvault-secrets

    # Airflow create user job settings
    createUserJob:
      useHelmHooks: false

    # Airflow database migration job settings
    migrateDatabaseJob:
      useHelmHooks: false

    # Ensure this goes on the correct node pool.
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: agentpool
              operator: In
              values:
                - poolz1
                - poolz2
                - poolz3  # Adjust these values to match your node pools

    topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          release: airflow  # Adjust to match your Helm release name

    # Tolerations should be defined outside of affinity
    tolerations:
      - effect: NoSchedule
        key: app
        value: "cluster"







