---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: flux-system
  labels:
    name: airflow
spec:
  targetNamespace: osdu-system
  releaseName: airflow
  dependsOn:
    - name: azure-keyvault-cache
      namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 10
      strategy: rollback
  test:
    enable: true
  interval: 10m0s
  chart:
    spec:
      chart: airflow
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: airflow-repo
        namespace: flux-system
  values:
    executor: LocalKubernetesExecutor
    data:
      metadataSecretName: postgresql-connection-string-secret
    postgresql:
      enabled: false
    dags:
      gitSync:
        enabled: true
        repo: 'https://github.com/polyseam/demo-dag-bag'
        credentialsSecret: airflow-git-credentials
        branch: main
        wait: 40
        subPath: dags
    enableBuiltInSecretEnvVars:
      AIRFLOW__CORE__FERNET_KEY: false
      AIRFLOW__WEBSERVER__SECRET_KEY: false
    fernetKeySecretName: keyvault-secrets
    webserverSecretKeySecretName: keyvault-secrets
    config:
      webserver:
        expose_config: 'True'
        instance_name: OSDU
        enable_proxy_fix: 'True'
        base_url: 'https://airflow.osdu.dev'
      operators:
        default_owner: OSDU
    logs:
      persistence:
        enabled: true
        size: 15Gi
        storageClassName: rwm
    createUserJob:
      useHelmHooks: false
    migrateDatabaseJob:
      useHelmHooks: false
