---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow
  namespace: flux-system
  labels:
    name: airflow
spec:
  targetNamespace: airflow
  releaseName: airflow
  dependsOn:
    - name: azure-keyvault-airflow
      namespace: default
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 10
      strategy: rollback
  test:
    enable: true
  interval: 10m0s
  chart:
    spec:
      chart: airflow
      # Specify the desired chart version if needed
      # version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: airflow-community
        namespace: flux-system
  values:
    # Set the Airflow version
    airflowVersion: "2.10.1"

    # Set the executor type
    executor: KubernetesExecutor

    # Set the Airflow Docker image tag
    images:
      airflow:
        tag: "2.10.1"

    # Environment Variables
    airflow:
      extraEnv:
        - name: ENVIRONMENT
          value: "dev"
        - name: CLOUD_PROVIDER
          value: "azure"
        - name: CI_COMMIT_TAG
          value: "v0.12.0"
        - name: BUILD_TAG
          value: "v0.12.0"
        - name: PYTHONPATH
          value: "/opt/airflow/dags:/opt/airflow"
        - name: AIRFLOW_VAR_AZURE_ENABLE_MSI
          value: "false"
        - name: AIRFLOW_VAR_ENTITLEMENTS_MODULE_NAME
          value: "entitlements_client"

      extraEnvFrom:
        - configMapRef:
            name: airflow-variables
        - configMapRef:
            name: airflow-service-endpoints
        - secretRef:
            name: airflow-variables

      # Install additional Python packages
      extraPipPackages:
        - "apache-airflow-providers-microsoft-azure"
        - "emoji"

      # Airflow Configuration
      config:
        AIRFLOW__METRICS__USE_PATTERN_MATCH: "True"
        AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
        AIRFLOW__LOGGING__ENABLE_TASK_CONTEXT_LOGGER: "False"
        AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
        AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
        AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
        AIRFLOW__WEBSERVER__AUTH_BACKEND: "airflow.contrib.auth.backends.password_auth"
        AIRFLOW__WEBSERVER__RBAC: "True"
        AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.default"
        AIRFLOW__CELERY__SSL_ACTIVE: "True"
        AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
        AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"
        AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
        AIRFLOW_VAR_CORE__CONFIG__DATALOAD_CONFIG_PATH: "/opt/airflow/dags/configs/dataload.ini"
        AIRFLOW__WEBSERVER__WORKERS: "8"
        AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE: "0"
        AIRFLOW__CORE__STORE_SERIALIZED_DAGS: "True"
        AIRFLOW__CORE__STORE_DAG_CODE: "True"
        AIRFLOW__WEBSERVER__WORKER_CLASS: "gevent"
        AIRFLOW__CELERY__WORKER_CONCURRENCY: "16"
        AIRFLOW_VAR_CORE__CONFIG__SHOW_SKIPPED_IDS: "True"
        AIRFLOW_VAR_ENV_VARS_ENABLED: "True"
      
      kubernetesPodTemplate:
        extraPipPackages:
          - "apache-airflow-providers-microsoft-azure"
          - "emoji"

    # DAGs Configuration
    dags:
      persistence:
        enabled: true
        existingClaim: airflow-dags-pvc
      gitSync:
        enabled: false

    # Logs Configuration
    logs:
      persistence:
        enabled: true
        existingClaim: airflow-logs-pvc

    # External PostgreSQL Configuration
    data:
      metadataSecretName: airflow-secrets

    # Disable Internal PostgreSQL and PgBouncer
    postgresql:
      enabled: false

    pgbouncer:
      enabled: false

    externalDatabase:
      type: postgres
      host: "airflow-cluster-rw.postgresql.svc.cluster.local"
      port: 5432
      database: "airflow-db"
      user: "dbuser"
      passwordSecret:
        name: "airflow-secrets"
        key: "db-password"

    # Enable StatsD
    statsd:
      enabled: true

    scheduler:
      logCleanup:
        enabled: false

    workers:
      logCleanup:
        enabled: false

    # Webserver Default User Configuration
    web:
      defaultUser:
        enabled: true
        existingSecret: airflow-secrets
        usernameKey: username
        passwordKey: password
        roleName: Admin
        email: admin@example.com
        firstName: admin
        lastName: user

    # Use Existing Secrets for Fernet and Webserver Secret Keys
    fernetKey:
      enabled: true
      existingSecret: keyvault-secrets
      existingSecretKey: AIRFLOW__CORE__FERNET_KEY
    webserverSecretKey:
      enabled: true
      existingSecret: keyvault-secrets
      existingSecretKey: AIRFLOW__WEBSERVER__SECRET_KEY

    # Affinity and Tolerations
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                    - poolz1
                    - poolz2
                    - poolz3

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            release: airflow

    tolerations:
      - effect: NoSchedule
        key: app
        value: "cluster"