---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow-official
  namespace: flux-system
spec:
  interval: 5m
  url: https://airflow.apache.org
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: airflow-community
  namespace: flux-system
spec:
  interval: 5m
  url: https://airflow-helm.github.io/charts