---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-airflow
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: airflow
  releaseName: keyvault-airflow
  chart:
    spec:
      chart: ./charts/keyvault-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    secrets:
      - secretName: keyvault-secrets 
        data:
          - key: fernet-key
            vaultSecret: airflow-fernet-key
          - key: webserver-key
            vaultSecret: airflow-webserver-key
          - key: azurestorageaccountname
            vaultSecret: system-storage
          - key: azurestorageaccountkey
            vaultSecret: system-storage-key
          - key: db-password
            vaultSecret: cpng-user-password