---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-auth
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  chart:
    spec:
      chart: ./charts/osdu-developer-auth
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-auth
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    hosts:
      - "*"
    gateways:
      - istio-system/internal-gateway
      - istio-system/external-gateway
    path: /auth/

