replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

serviceAccount:
  create: true
  name: "" 

azureWorkloadIdentity:
  clientId: ""
  tenantId: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

azure:
  enabled: false

env:
- name: MESSAGE
  value: Hello World!
- name: FROM_CONFIG_MAP
  valueFrom:
    configMapKeyRef:
      name: "{{ include \"env-debug.fullname\" . }}-config"
      key: MESSAGE
