replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

autoscaling:
  enabled: false

azure:
  enabled: false

env:
- name: MESSAGE
  value: Hello World!
- name: FROM_CONFIG_MAP
  valueFrom:
    configMapKeyRef:
      name: "{{ include \"env-debug.fullname\" . }}-config"
      key: MESSAGE
