---
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-profile
  namespace: istio-system
spec:
  profile: default
  hub: "docker.io/istio"
  tag: "1.15.1"
  components:
    pilot:
      enabled: true
    cni:
      enabled: false
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          hpaSpec:
            minReplicas: 2
    egressGateways:
      - name: istio-egressgateway
        enabled: false
