apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-config-job-cluster-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-config-job-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: workload-identity-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: dns-config-job-cluster-reader
  apiGroup: rbac.authorization.k8s.io
