apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dns-configuration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dns-configuration.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "dns-configuration.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ include "dns-configuration.serviceAccountName" . }}
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: {{ include "dns-configuration.fullname" . }}-script
          defaultMode: 0755
      - name: azure-identity-token
        projected:
          sources:
          - serviceAccountToken:
              path: azure-identity-token
              expirationSeconds: 3600
              audience: api://AzureADTokenExchange
      containers:
      - name: dns-config
        image: "mcr.microsoft.com/azure-cli:latest"
        imagePullPolicy: IfNotPresent
        command: ["/scripts/configure-dns.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
        - name: azure-identity-token
          mountPath: /var/run/secrets/azure/tokens
          readOnly: true
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
        env:
        - name: AZURE_CLIENT_ID
          value: {{ .Values.azure.clientId | quote }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.azure.tenantId | quote }}
        - name: AZURE_SUBSCRIPTION
          value: {{ .Values.azure.subscription | quote }}
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/azure/tokens/azure-identity-token
        - name: RESOURCE_GROUP
          value: {{ .Values.azure.resourceGroup | quote }}
        - name: AKS_NAME
          value: {{ .Values.azure.aksName | quote }}
        - name: DNS_NAME
          value: {{ .Values.azure.dnsName | quote }}
        - name: MAX_RETRIES
          value: "60"
        - name: RETRY_INTERVAL
          value: "10"
        - name: ISTIO_SERVICE_NAME
          value: "istio-ingressgateway"
        - name: ISTIO_NAMESPACE
          value: "istio-system"
        - name: AZURE_AUTHORITY_HOST
          value: "https://login.microsoftonline.com/"