apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dns-configuration.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dns-configuration.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "dns-configuration.selectorLabels" . | nindent 8 }}
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: {{ include "dns-configuration.serviceAccountName" . }}
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: {{ include "dns-configuration.fullname" . }}-script
          defaultMode: 0755
      - name: azure-identity-token
        projected:
          sources:
          - serviceAccountToken:
              path: azure-identity-token
              expirationSeconds: 3600
              audience: api://AzureADTokenExchange
      containers:
      - name: dns-config
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
        imagePullPolicy: {{ .Values.job.image.pullPolicy }}
        command: ["/scripts/configure-dns.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
        - name: azure-identity-token
          mountPath: /var/run/secrets/azure/tokens
          readOnly: true
        resources:
          {{- toYaml .Values.job.resources | nindent 10 }}
        env:
        - name: AZURE_CLIENT_ID
          value: {{ .Values.azure.clientId | quote }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.azure.tenantId | quote }}
        - name: AZURE_SUBSCRIPTION
          value: {{ .Values.azure.subscription | quote }}
        - name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/azure/tokens/azure-identity-token
        - name: RESOURCE_GROUP
          value: {{ .Values.azure.resourceGroup | quote }}
        - name: AKS_NAME
          value: {{ .Values.azure.aksName | quote }}
        - name: UNIQUE_ID
          value: {{ .Values.azure.uniqueId | quote }}
        - name: MAX_RETRIES
          value: "{{ .Values.dns.maxRetries }}"
        - name: RETRY_INTERVAL
          value: "{{ .Values.dns.retryInterval }}"
        - name: ISTIO_SERVICE_NAME
          value: {{ .Values.istio.serviceName }}
        - name: ISTIO_NAMESPACE
          value: {{ .Values.istio.namespace }}
        - name: AZURE_AUTHORITY_HOST
          value: "https://login.microsoftonline.com/"