apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-configmap-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-configmap-manager-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: workload-identity-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: dns-configmap-manager
  apiGroup: rbac.authorization.k8s.io
