# HTTPRoute for web-site application
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-site-route
  namespace: web-site
spec:
  parentRefs:
  - name: external-gateway
    namespace: istio-system
  - name: internal-gateway
    namespace: istio-system
  rules:
  # Route all web traffic to the web service
  # ACME challenge paths are handled by the higher-priority route in istio-system
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    backendRefs:
    - name: osdu-developer-web-service
      port: 80
      weight: 100
