---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis-cache
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis-cache
  install:
    remediation:
      retries: 3
  interval: 10m0s
  releaseName: redis
  values:
    cluster:
      enabled: true
      slaveCount: 3
    auth:
      enabled: false
    master:
      port: 6379
      service:
        type: ClusterIP
      livenessProbe:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 5
      readinessProbe:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 5
      tolerations:
        - effect: NoSchedule
          key: app
          value: "cluster"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - poolz1
                      - poolz2
                      - poolz3
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - eastus2-1 # THIS DEPENDS ON LOCATION
                      - eastus2-2 # THIS DEPENDS ON LOCATION
                      - eastus2-3 # THIS DEPENDS ON LOCATION
      persistence:
        enabled: true
        size: 8Gi
        accessModes:
        - ReadWriteOnce
      replicaCount: 1
    replica:
      tolerations:
        - effect: NoSchedule
          key: app
          value: "cluster"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: agentpool
                    operator: In
                    values:
                      - poolz1
                      - poolz2
                      - poolz3
              - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - eastus2-1 # THIS DEPENDS ON LOCATION
                      - eastus2-2 # THIS DEPENDS ON LOCATION
                      - eastus2-3 # THIS DEPENDS ON LOCATION
      persistence:
        enabled: true
        size: 8Gi
        accessModes:
        - ReadWriteOnce
      replicaCount: 1
