apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: redis
  namespace: redis-cache
spec:
  interval: 10m
  url: https://charts.bitnami.com/bitnami
  # type: oci
  # url: oci://registry-1.docker.io/bitnamicharts/redis
