---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ./deploy/eck-operator
      sourceRef:
        kind: GitRepository
        name: elastic-operator
        namespace: elastic-system
      interval: 12h
  # values:
  #   podLabels:
  #     traffic.sidecar.istio.io/excludeInboundPorts: "9443"
  #     traffic.sidecar.istio.io/includeInboundPorts: '*'
