---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-developer-base-core
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: osdu-core
  chart:
    spec:
      chart: ./charts/osdu-developer-base
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    enableRequestAuthentication: true
    azure:
      enabled: true
    resourceLimits:
      defaultCpuRequests: "0.5"
      defaultMemoryRequests: "1Gi"
      defaultCpuLimits: "2"
      defaultMemoryLimits: "4Gi"