---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: file
  namespace: osdu-core
spec:
  host: file.osdu-core.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: file
  namespace: osdu-core
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/internal-gateway
  - istio-system/external-gateway
  http:
  - match:
    - uri:
        prefix: "/api/file/"
    route:
    - destination:
        host: file.osdu-core.svc.cluster.local
        # subset: v1
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: file-service
  namespace: flux-system
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
  - name: osdu-developer-base
    namespace: default
  targetNamespace: osdu-core
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  values:
    subset: v2
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
    configuration:
    - service: file
      repository: community.opengroup.org:5555/osdu/platform/system/file/file-release-0-22
      tag: latest
      path: /api/file/*
      probe:
        path: /api/file/v2/readiness_check
        port: http
      keyvault: true
      auth:
        disable:
          - "/"
          - "*/index.html"
          - "*/v2/api-docs"
          - "*/swagger-resources"
          - "*/swagger-ui.html"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/file/swagger-resources/*"
          - "/api/file/webjars/*"
          - "*/actuator/health"
          - "*/health"
      env:
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URL
        secret:
          name: azure-resources
          key: keyvault-uri
      - name: APPINSIGHTS_KEY
        secret:
          name: azure-resources
          key: insights-key
      - name: AZURE_AD_APP_RESOURCE_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AAD_CLIENT_ID
        value: ${AZURE_CLIENT_ID}
      - name: AZURE_ISTIOAUTH_ENABLED
        value: "true"
      - name: AZURE_PAAS_PODIDENTITY
        value: "true"
      - name: SERVER_SERVLET_CONTEXTPATH
        value: "/api/file/"
      - name: SERVER_PORT
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: SPRING_APPLICATION_NAME
        value: "file"
      - name: SPRING_CONFIG_NAME
        value: "common,application"
      - name: LOG_PREFIX
        value: file
      - name: LOGGING_LEVEL
        value: INFO
      - name: APPLICATION_PORT
        value: 80
      - name: COSMOSDB_DATABASE
        value: osdu-db
      - name: OSDU_ENTITLEMENTS_APP_KEY
        value: OBSOLETE
      - name: PARTITION_SERVICE_ENDPOINT
        value: "http://partition/api/partition/v1"
      - name: OSDU_ENTITLEMENTS_URL
        value: http://entitlements/api/entitlements/v2
      - name: authorizeAPI
        value: http://entitlements/api/entitlements/v2
      - name: OSDU_STORAGE_URL
        value: http://storage/api/storage/v2
      - name: SEARCH_HOST
        value: http://search/api/search/v2
      - name: AZURE_PUBSUB_PUBLISH
        value: "true"
      - name: EVENT_GRID_ENABLED_STATUS
        value: "false"
      - name: EVENT_GRID_TOPIC_STATUS
        value: "statuschangedtopic"
      - name: SERVICE_BUS_ENABLED_STATUS
        value: "true"
      - name: SERVICE_BUS_TOPIC_STATUS
        value: "statuschangedtopic"
      - name: BATCH_SIZE
        value: "100"
      - name: SEARCH_QUERY_LIMIT
        value: "1000"
      - name: FILE_CHECKSUM_CALCULATION_LIMIT
        value: "5368709120L"