---
apiVersion: v1
kind: Namespace
metadata:
  name: osdu-core
  labels:
    toolkit.fluxcd.io/tenant: dev-team
    istio-injection: enabled
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: osdu-core
spec:
  mtls:
    mode: STRICT