---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-init
  namespace: osdu-core
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
    - name: osdu-developer-base
      namespace: default
    - name: partition
      namespace: flux-system
  targetNamespace: osdu-core
  chart:
    spec:
      chart: ./charts/osdu-developer-init
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    partition: opendes
  valuesFrom:
    - kind: ConfigMap
      name: configmap-services
      valuesKey: client_id
      targetPath: client_id
    - kind: ConfigMap
      name: configmap-services
      valuesKey: tenant_id
      targetPath: tenant_id
    - kind: ConfigMap
      name: configmap-services
      valuesKey: partition_servicebus_name_0
      targetPath: service_bus
    - kind: Secret
      name: active-directory
      valuesKey: principal-clientid
      targetPath: client_secret

