---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osdu-workflow
  namespace: osdu-core
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  dependsOn:
    - name: osdu-partition
      namespace: osdu-core
  targetNamespace: osdu-core
  chart:
    spec:
      chart: ./charts/osdu-developer-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: configmap-software
      valuesKey: value.yaml
  values:
    nameOverride: workflow
    installationType: osduCore
    subset: m24
    replicaCount: 1
    service:
      type: ClusterIP
      port: 80
    configuration:
    - service: legal
      path: /api/workflow/
      hosts:
        - "*"
      gateways:
        - istio-system/internal-gateway
        - istio-system/external-gateway
      repository: community.opengroup.org:5555/osdu/platform/data-flow/ingestion/ingestion-workflow/ingestion-workflow-
      tag: latest 
      probe:
        path: /actuator/health
        port: 8081
        liveness:
          delay: 250
          seconds: 10
      keyvault: true
      auth:
        disable:
          - "*/actuator/health"
          - "*/health"
          - "*/_ah/**"
          - "*/configuration/ui"
          - "*/configuration/security"
          - "/api/workflow/v3/info"
          - "/api/workflow/v3/swagger*"
          - "/api/workflow/v3/api-docs*"
          - "/api/workflow/v3/webjars/*"          
      env:
      - name: AZURE_TENANT_ID
        secret:
          name: active-directory
          key: tenant-id
      - name: AZURE_SUBSCRIPTION_ID
        secret:
          name: active-directory
          key: subscription-id
      - name: AZURE_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: AZURE_CLIENT_SECRET
        secret:
          name: active-directory
          key: principal-clientpassword
      - name: KEYVAULT_URI
        secret:
          name: azure-resources
          key: keyvault-uri
      - name: AAD_CLIENT_ID
        secret:
          name: active-directory
          key: principal-clientid
      - name: APPINSIGHTS_KEY
        secret:
          name: azure-resources
          key: insights-key
      - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        secret:
          name: azure-resources
          key: insights-connection
      - name: AZURE_ISTIOAUTH_ENABLED
        value: "true"
      - name: AZURE_PAAS_PODIDENTITY_ISENABLED
        value: "false"
      - name: SERVER_SERVLET_CONTEXTPATH
        value: "/api/workflow/"
      - name: SERVER_PORT
        value: "80"
      - name: ACCEPT_HTTP
        value: "true"
      - name: SPRING_APPLICATION_NAME
        value: "legal"
      - name: SPRING_CONFIG_NAME
        value: "common,application"
      - name: LOG_PREFIX
        value: "workflow"
      - name: AZURE_STORAGE_ENABLE_HTTPS
        value: "true"
      - name: COSMOSDB_DATABASE
        value: "osdu-db"
      - name: OSDU_AIRFLOW_URL
        value: "http://airflow-webserver.airflow.svc.cluster.local/airflow"
      - name: OSDU_AIRFLOW_USERNAME
        secret:
          name: azure-resources
          key: airflow-username
      - name: OSDU_AIRFLOW_PASSWORD
        secret:
          name: azure-resources
          key: airflow-password
      - name: OSDU_AIRFLOW_VERSION2_ENABLED
        value: true
      - name: PARTITION_SERVICE_ENDPOINT
        value: "http://partition/api/partition/v1"
      - name: OSDU_ENTITLEMENTS_URL
        value: "http://entitlements/api/entitlements/v2"
      - name: OSDU_ENTITLEMENTS_URL
        value: "OBSOLETE"