---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stakater-reloader
  namespace: reloader
spec:
  targetNamespace: reloader
  chart:
    spec:
      chart: reloader
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    nameOverride: reloader
    reloader:
      watchGlobally: true