FROM mcr.microsoft.com/azure-cli:latest

# Install OS packages
RUN apk add --no-cache curl ncurses

# Install azd
RUN curl -fsSL https://aka.ms/install-azd.sh | bash

# Copy the script into the container
COPY functions.sh /usr/local/bin/functions.sh
COPY hook-postprovision.sh /usr/local/bin/postprovision.sh
COPY hook-preprovision.sh /usr/local/bin/preprovision.sh

# Create a directory to work in
WORKDIR /workspace

# Make the script executable
RUN chmod +x /usr/local/bin/functions.sh \
    && chmod +x /usr/local/bin/postprovision.sh \
    && chmod +x /usr/local/bin/preprovision.sh 

# Set the entrypoint to run your script
CMD ["/bin/bash"]
