FROM mcr.microsoft.com/cbl-mariner/base/azure-cli:2

# Install required packages
RUN tdnf update -y && \
  tdnf install -y curl gawk ncurses && \
  rm -rf /var/cache/tdnf/*

# Install azd
RUN curl -fsSL https://aka.ms/install-azd.sh | bash

# Copy the script into the container
COPY functions.sh /usr/local/bin/functions.sh
COPY hook-preprovision.sh /usr/local/bin/preprovision.sh

# Create a directory to work in
WORKDIR /workspace

# Make the script executable
RUN chmod +x /usr/local/bin/functions.sh \
    && chmod +x /usr/local/bin/preprovision.sh 

# Set the entrypoint to run your script
CMD ["/bin/bash"]
