
fullnameOverride: blob-upload

global:
  configmapNamespace: osdu-core

azure:
  tenantId: <tenant_id>
  clientId: <managed_identity_clientid>
  resourceGroup: <rg_name>

blobUpload:
  enabled: false
  container: "legal-service-azure-configuration"
