---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  chart:
    spec:
      chart: manifests/charts/base
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  releaseName: istio-operator
  chart:
    spec:
      chart: manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    hub: "docker.io/istio"
    tag: "1.17.8"
