---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: istio
  namespace: istio-system
spec:
  interval: 30m
  url: https://github.com/istio/istio
  ref:
    branch: master
    tag: 1.15.1
