---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: software-component-certificates
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/cert-manager
  prune: true
  wait: true
  healthChecks:
    - kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: software-component-redis
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/redis-cache
  prune: true
  wait: true
  healthChecks:
    - kind: StatefulSet
      name: redis-master
      namespace: redis-cache
    - kind: StatefulSet
      name: redis-replicas
      namespace: redis-cache
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: software-component-elastic
  namespace: flux-system
spec:
  dependsOn:
    - name: software-component-certificates
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/elastic-operator
  prune: true
  wait: true
  healthChecks:
    - kind: StatefulSet
      name: elastic-system
      namespace: elastic-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: software-configuration-elastic
  namespace: flux-system
spec:
  dependsOn:
    - name: software-component-elastic
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/configuration/elastic
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: software-component-istio
  namespace: flux-system
spec:
  dependsOn:
    - name: software-component-certificates
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/components/istio-ingress
  prune: true
  wait: true
  healthChecks:
    - kind: Gateway
      name: istio-external-gateway
      namespace: aks-istio-ingress
    - kind: Gateway
      name: istio-internal-gateway
      namespace: aks-istio-ingress
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: software-configuration-config-maps
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./software/configuration/config-maps
  prune: true
  wait: true