---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  releaseName: prometheus-operator
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    alertmanager:
      alertmanagerSpec:
        tolerations:
          - effect: NoSchedule
            key: app
            value: "cluster"
    prometheusOperator:
      tolerations:
        - effect: NoSchedule
          key: app
          value: "cluster"
    kube-state-metrics:
      tolerations:
        - effect: NoSchedule
          key: app
          value: "cluster"
    grafana:
      tolerations:
        - effect: NoSchedule
          key: app
          value: "cluster"
      grafana.ini:
        auth.anonymous:
          enabled: true
          org_name: Main Org.
          org_role: Editor
        auth:
          disable_login_form: true
    prometheus:
      prometheusSpec:
        tolerations:
          - effect: NoSchedule
            key: app
            value: "cluster"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: monitoring
spec:
  releaseName: jaeger-operator
  chart:
    spec:
      chart: jaeger-operator
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: monitoring
spec:
  releaseName: kiali-operator
  chart:
    spec:
      chart: kiali-operator
      sourceRef:
        kind: HelmRepository
        name: kiali
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      repo: quay.io/kiali/kiali-operator
      tag: latest