# -------HTTP REST CLIENT -------
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

## This script provides a few samples for calling unit.



# -----------------------
# OAUTH (Variables)
# -----------------------
###
@login_base = login.microsoftonline.com/{{TENANT_ID}}
@oauth_token_host = {{login_base}}/oauth2/v2.0/token
@scopes = {{CLIENT_ID}}/.default openid profile offline_access



# -----------------------
# OAUTH  refresh_token
# -----------------------
###
# @name refresh
POST https://{{oauth_token_host}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&client_id={{CLIENT_ID}}
&client_secret={{CLIENT_SECRET}}
&refresh_token={{REFRESH_TOKEN}}
&scope={{scopes}}


# -----------------------
# API (Variables)
# -----------------------
###
@access_token = {{refresh.response.body.access_token}}
@UNIT_HOST = {{HOST}}/api/unit
@data_partition_id = opendes

# -----------------------
# API: Version
# -----------------------

###
# @name info
GET {{UNIT_HOST}}/v3/info
Authorization: Bearer {{access_token}}
Accept: application/json

# -----------------------
# API: unit
# -----------------------

###
# @name getUnit
GET {{UNIT_HOST}}/v3/unit
Authorization: Bearer {{access_token}}
Accept: application/json
data-partition-id: {{data_partition_id}}


###
# @name getCatalog
GET {{UNIT_HOST}}/v3/catalog
Authorization: Bearer {{access_token}}
Accept: application/json
data-partition-id: {{data_partition_id}}

###
# @name getMeasurement
GET {{UNIT_HOST}}/v3/measurement/list
Authorization: Bearer {{access_token}}
Accept: application/json
data-partition-id: {{data_partition_id}}

###
# @name getUnitMaps
GET {{UNIT_HOST}}/v3/unit/maps
Authorization: Bearer {{access_token}}
Accept: application/json
data-partition-id: {{data_partition_id}}

###
# @name getUnitSystems
GET {{UNIT_HOST}}/v3/unitsystem/list
Authorization: Bearer {{access_token}}
Accept: application/json
data-partition-id: {{data_partition_id}}