
fullnameOverride: osdu-svc

################################################################################
# Specify the azure environment specific values
#
azure:
  enabled: true
  tenantId: <tenant_id>
  clientId: <managed_identity_clientid>
  keyvaultName: <keyvault_name>

################################################################################
# Specify the resource limits
#
resourceLimits:
  defaultCpuRequests: "0.5"
  defaultMemoryRequests: "4Gi"
  defaultCpuLimits: "1"
  defaultMemoryLimits: "4Gi"

blobUpload:
  enabled: false
  container: "legal-service-azure-configuration"

share:
  enabled: false
  items:
    - name: folder
      file: "file"
      url: "https://example.com/folder/file.json"
    - name: item2
      url: "https://example.com/archive.tar.gz"
      file: "folder_in_archive"
      compress: true

