apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: elasticsearch-vs
  namespace: elastic-search
spec:
  hosts:
  - "*" # Match all hosts
  gateways:
  - istio-system/internal-gateway
  - istio-system/external-gateway
  http:
  - match:
    - uri:
        prefix: /elastic
    route:
    - destination:
        host: elasticsearch-es-http.elastic-search.svc.cluster.local
        port:
          number: 9200
    rewrite:
      uri: "/"
