---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-keyvault-credentials
  namespace: default
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: elastic-search
  chart:
    spec:
      chart: ./charts/keyvault-secrets
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: config-map-values
      valuesKey: values.yaml
  values:
    secrets:
      - secretName: elasticsearch-credentials
        data:
          - key: username
            vaultSecret: opendes-elastic-username
          - key: password
            vaultSecret: opendes-elastic-password
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-search-init
  namespace: elastic-search
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  targetNamespace: elastic-search
  chart:
    spec:
      chart: ./charts/osdu-developer-init
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  install:
    remediation:
      retries: 3
  values:
    jobs:
      partitionInit: false
      entitlementInit: false
      userInit: false
      schemaInit: false
      elasticInit: true