name: Auto - Documentation

on:
  # Trigger spell check on pull requests
  pull_request:
    paths:
      - "**/*.md"
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - 'docs/src/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Spell Check job
  SpellCheck:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Typo file contents check
        shell: bash
        run: cat ./.github/_typos.toml
      # https://github.com/crate-ci/typos
      - name: Check spelling of markdown files
        uses: crate-ci/typos@master
        with:
          files: ./**/*.md
          config: ./.github/_typos.toml

  # Deployment job
  Deploy:
    needs: SpellCheck  # Run only after SpellCheck job is successful
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-mermaid2-plugin
      - run: |
          cd docs
          mkdocs gh-deploy --force --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}