on:
  pull_request:
    paths:
      - "*.md"
      - "docs/*.md"
  workflow_dispatch:

name: Auto - Documentation Check
jobs:
  SpellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Typo file contents check
        shell: bash
        run: cat ./.github/_typos.toml

      # https://github.com/crate-ci/typos
      - name: Check spelling of markdown files
        uses: crate-ci/typos@master
        with:
          files: ./**/*.md
          config: ./.github/_typos.toml