name: Infra - Release

on:
  workflow_dispatch:

env:
  CLI_VERSION: latest

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Install Bicep
        shell: pwsh
        run: |
          az config set bicep.use_binary_from_path=False
          az bicep install   

      - name: Bicep build
        shell: pwsh
        run: |
          /home/runner/.azure/bin/bicep build bicep/main.bicep --outfile azuredeploy.json

      - name: Github Checkin
        uses: EndBug/add-and-commit@v9
        with:
          message: "Initialize Software Install"
          add: "."

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Find Latest Tag
        uses: oprypin/find-latest-tag@v1.1.1
        id: latest
        with:
          repository: ${{ github.repository }}

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.latest.outputs.tag }}
          artifacts: "azuredeploy.json"
